server:
  port: 7001
eureka:
  instance:
    hostname: mybatis-eureka
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false
    fetch-registry: false