spring:
  application:
    name: mybatis-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.infoex.pojo

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka
